FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 5000

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["src/SwiftBite.ApiGateway/SwiftBite.ApiGateway.csproj", "src/SwiftBite.ApiGateway/"]
RUN dotnet restore "src/SwiftBite.ApiGateway/SwiftBite.ApiGateway.csproj"

COPY . .
WORKDIR "/src/src/SwiftBite.ApiGateway"
RUN dotnet build "SwiftBite.ApiGateway.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SwiftBite.ApiGateway.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SwiftBite.ApiGateway.dll"]